name: build

on:
  pull_request:
    branches:
    - main
    paths:
    - 'src/**/*.scala'
    - '.github/**'
  
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sammyne/scala:2.12.10-konajdk8.0.12-ubuntu20.04
    steps:
    # sammyne/scala bundled without git, so installing it to avoid the RESTful fallback of actions/check.
    # Otherwise, the fetched repository won't be a valid git repository.
    - name: Install git
      run: apt update && apt install -y git
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Scala toolchains
      run: |
        scalac -version &&
        sbt --version
    - name: Run unit tests
      run: sbt test
